spring:
  application:
    name: NotificationService

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        transport:
          protocol: smtp
        debug: true

cloud:
  aws:
    region:
      auto: true
      static: eu-north-1
    credentials:
      access-key: "${AWS_ACCESS_KEY}"
      secret-key: "${AWS_SECRET_KEY}"
    sender: "${AWS_SENDER_EMAIL}"

notification-service:
  email.enabled: true
  sms.enabled: true
  push.enabled: true