spring:
  application:
    name: NotificationService

cloud:
  aws:
    region:
      auto: true
      static: eu-north-1
    credentials:
      access-key: "${AWS_ACCESS_KEY}"
      secret-key: "${AWS_SECRET_KEY}"
    sender: "${AWS_SENDER_EMAIL}"

notification-service:
  email.enabled: true
  sms.enabled: true
  push.enabled: true